/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Objects;
import java.util.Scanner;
import java.util.stream.Stream;

public class App {


    public static void main(String[] args) {
        checksemicolon("C:\\Users\\STUDENT\\project\\java-fundamentals\\linter\\resources\\gates.js");
    }
    public static void checksemicolon(String path) {
        int numline=1;
        try {
            // initialize lines stream
            Stream<String> stream = Files.lines(Paths.get(path));

            // apply filter & sorting
            int currentLine = new Throwable().getStackTrace()[0].getLineNumber();

            stream.filter(l -> ! (l.endsWith(";")||l.endsWith("{")||l.endsWith("}")||(l.contains("if"))||l.contains("else")||l.isEmpty()))

                    .sorted()

                    .map(String::toUpperCase)
                    .forEach(l -> System.out.println("line"+ currentLine));

             System.out.printf("There are %d even numbers in the stream %n", numline);
//            int currentLine = new Throwable().getStackTrace()[0].getLineNumber();
            System.out.println("The Current Line Number is " + currentLine);
            // close the stream
            stream.close();

        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }
}
